<?php

declare(strict_types=1);
$config=require __DIR__.'/config.php'; require_once __DIR__.'/includes/database.php'; require_once __DIR__.'/includes/functions.php'; require_once __DIR__.'/includes/auth.php'; require_once __DIR__.'/includes/csrf.php'; require_once __DIR__.'/includes/email.php';
if(is_logged_in()) redirect('/dashboard/');
$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$account=trim($_POST['account']??'');$password=$_POST['password']??'';if($account===''||$password==='')$error='请输入用户名/邮箱和密码';else{try{$stmt=db()->prepare('SELECT id,username,email,password,status,email_verified_at,oauth_provider FROM users WHERE username=? OR email=? LIMIT 1');$stmt->execute([$account,$account]);$u=$stmt->fetch();if(!$u)$error='用户名/邮箱或密码错误';elseif((int)$u['status']!==1)$error='你的账号已被禁用';elseif(!empty($u['oauth_provider']))$error='该账号使用阿宅账号登录，请使用阿宅账号登录';elseif(empty($u['email_verified_at']))$error='请先验证邮箱后再登录。<a href="/resend_verification.php">重新发送验证邮件</a>';elseif(empty($u['password'])||!password_verify($password,$u['password']))$error='用户名/邮箱或密码错误';else{login_user((int)$u['id'],$u['username']);if(password_needs_rehash($u['password'],PASSWORD_DEFAULT)){db()->prepare('UPDATE users SET password=?,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([password_hash($password,PASSWORD_DEFAULT),(int)$u['id']]);}log_action((int)$u['id'],null,'login',$u['username']);redirect('/dashboard/');}}catch(Throwable $e){error_log('[AZhai Sub Login] '.$e->getMessage());$error='登录失败，请稍后重试';}}}
$pageTitle='登录'; require __DIR__.'/includes/header.php';
?><div class="card narrow"><h1>登录</h1><?php if($error):?><div class="alert danger"><?= $error ?></div><?php endif;?><?php if($m=flash('success')):?><div class="alert success"><?=e($m)?></div><?php endif;?><form method="post"><?=csrf_field()?><div class="form-group"><label>用户名 / 邮箱</label><input type="text" name="account" value="<?=e($_POST['account']??'')?>" autocomplete="username" required autofocus></div><div class="form-group"><label>密码</label><input type="password" name="password" autocomplete="current-password" required></div><button class="primary">登录</button></form><div style="margin-top:14px;text-align:right;font-size:12px"><a href="/forgot_password.php">忘记密码？</a></div><div style="display:flex;align-items:center;gap:10px;margin:20px 0;color:#c4bbc0;font-size:11px"><span style="flex:1;height:1px;background:#f2e7eb"></span><span>或者</span><span style="flex:1;height:1px;background:#f2e7eb"></span></div><a href="/oauth/login.php?return_to=%2Fdashboard%2F" class="oauth-login-button"><span class="oauth-login-icon">🌸</span><span>使用阿宅账号登录</span></a><div style="margin-top:18px;text-align:center;color:#aaa1a8;font-size:12px">还没有账号？ <a href="/register.php" style="color:#f2769a;font-weight:650">注册账号</a></div></div><?php require __DIR__.'/includes/footer.php'; ?>
